### ISSUE TITLE
Incorrect selector (.list-items > .list-item.c300x300.:nth-child(2)) generated possibly due to an empty string class

### ISSUE THREAD

**Issue by venkatkarun** [Autarc/optimal-select#7]
`<article class="list-item c300x300 "></article>` is the parent element with the incorrect expression and please note the error space in `class` and the extra dot in .list-item.c300x300**.**

```
Error: Syntax error, unrecognized expression: .list-items > .list-item.c300x300.:nth-child(2)
  at Function.Sizzle.error (chrome-extension://bekccbechiigcepdoebmbganlaehelkj/bower_components/jquery/dist/jquery.js:1458:8)
  at Sizzle.tokenize (chrome-extension://bekccbechiigcepdoebmbganlaehelkj/bower_components/jquery/dist/jquery.js:2075:11)
  at Sizzle.select (chrome-extension://bekccbechiigcepdoebmbganlaehelkj/bower_components/jquery/dist/jquery.js:2479:20)
  at Function.Sizzle [as find] (chrome-extension://bekccbechiigcepdoebmbganlaehelkj/bower_components/jquery/dist/jquery.js:855:9)
  at jQuery.fn.extend.find (chrome-extension://bekccbechiigcepdoebmbganlaehelkj/bower_components/jquery/dist/jquery.js:2695:11)
...
```

![css_selector_creating_spaces](https://cloud.githubusercontent.com/assets/15202800/14490546/ce6fc65a-0149-11e6-82f1-214a1faa2474.png)

**Comment by Autarc** [comment]
Are you sure you're using the latest version (v2.2.0) ? With the previous update @pauloborges [fixed the issue](https://github.com/Autarc/optimal-select/pull/6) in case additional whitespaces are wrapped around classnames. It sounds like the same problem you have. Since I don't which website you were inspecting I tried to create a similar structure based on your provided screenshot. Using the latest builts of library it works for me:
![classname-whitespace-error- 7](https://cloud.githubusercontent.com/assets/1060490/14510657/5ebee58a-01ca-11e6-9a67-fc48a54b2e75.png)

**Comment by venkatkarun** [comment]
thanks for the quick update and double checking with a similar structure, Stefan. Closing the issue.
